Other models that can be created using iris dataset

Importing and loading the necessary libraries and dataset

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

# Load the Iris dataset
data = load_iris()
X = data.data  # Features
y = data.target  # Labels

# Split data into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardizing the features (Important for SVM)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


 Support Vector Machine (SVM)
 
SVM is a powerful classification algorithm that finds the optimal boundary (hyperplane) to separate different classes. It works well with both linear and non-linear data using kernels. SVM is effective for small to medium-sized datasets but can be slow for large datasets.

In [2]:
# Train the SVM model
svm_model = SVC(kernel='linear')  # Using linear kernel
svm_model.fit(X_train, y_train)

# Predict & Evaluate
y_pred_svm = svm_model.predict(X_test)
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"SVM Accuracy: {accuracy_svm * 100:.2f}%")


SVM Accuracy: 96.67%


Decision Tree

A decision tree is a simple yet powerful model that splits data based on feature conditions to make predictions. It is easy to interpret but can overfit if not pruned properly. Works well for small datasets and rule-based decision-making.

In [3]:
# Train the Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# Predict & Evaluate
y_pred_dt = dt_model.predict(X_test)
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print(f"Decision Tree Accuracy: {accuracy_dt * 100:.2f}%")


Decision Tree Accuracy: 100.00%


Random Forest

Random Forest is an ensemble learning method that combines multiple decision trees to improve accuracy and reduce overfitting. It is robust to noise and works well on large datasets. However, it can be slower and less interpretable than a single decision tree.

In [4]:
# Train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Predict & Evaluate
y_pred_rf = rf_model.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf * 100:.2f}%")


Random Forest Accuracy: 100.00%


The models don't just give accuracy; you can also evaluate them using other metrics like precision, recall, F1-score, and confusion matrix for deeper insights. Here’s how you can get more performance metrics:

In [5]:
from sklearn.metrics import classification_report, confusion_matrix

# Function to evaluate models
def evaluate_model(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    
    # Accuracy
    accuracy = accuracy_score(y_test, y_pred) * 100
    print(f"\n🔹 {model_name} Accuracy: {accuracy:.2f}%\n")

    # Confusion Matrix
    print(f"📊 Confusion Matrix for {model_name}:")
    print(confusion_matrix(y_test, y_pred))

    # Classification Report (Precision, Recall, F1-score)
    print(f"\n📌 Classification Report for {model_name}:")
    print(classification_report(y_test, y_pred))

# Evaluate SVM
evaluate_model(svm_model, X_test, y_test, "SVM")

# Evaluate Decision Tree
evaluate_model(dt_model, X_test, y_test, "Decision Tree")

# Evaluate Random Forest
evaluate_model(rf_model, X_test, y_test, "Random Forest")



🔹 SVM Accuracy: 96.67%

📊 Confusion Matrix for SVM:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]

📌 Classification Report for SVM:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30


🔹 Decision Tree Accuracy: 100.00%

📊 Confusion Matrix for Decision Tree:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

📌 Classification Report for Decision Tree:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg  